"""
FloodSense AI — District Data Service
Historical vulnerability scores, elevation, terrain type, and 2022 flood impact data.
"""

from dataclasses import dataclass

@dataclass
class DistrictInfo:
    name: str
    name_ur: str
    province: str
    avg_elevation_m: float
    terrain_type: str
    terrain_type_ur: str
    vulnerability_score: float   # 0–1, higher = more vulnerable
    population_thousands: int
    lat: float
    lon: float
    rivers: list[str]
    flood_history_events: int    # documented events since 2000
    casualties_2022: int         # 2022 super-floods
    displaced_2022: int          # thousands displaced
    ndma_risk_zone: str          # A/B/C


DISTRICTS: dict[str, DistrictInfo] = {
    "buner": DistrictInfo(
        name="Buner", name_ur="بونیر",
        province="KPK",
        avg_elevation_m=1082,
        terrain_type="Hilly", terrain_type_ur="پہاڑی",
        vulnerability_score=0.78,
        population_thousands=900,
        lat=34.55, lon=72.50,
        rivers=["Barandu River", "Khindi Khwar"],
        flood_history_events=14,
        casualties_2022=38, displaced_2022=45,
        ndma_risk_zone="A",
    ),
    "swat": DistrictInfo(
        name="Swat", name_ur="سوات",
        province="KPK",
        avg_elevation_m=980,
        terrain_type="Valley", terrain_type_ur="وادی",
        vulnerability_score=0.85,
        population_thousands=2300,
        lat=35.22, lon=72.42,
        rivers=["Swat River", "Ushu River"],
        flood_history_events=22,
        casualties_2022=95, displaced_2022=210,
        ndma_risk_zone="A",
    ),
    "nowshera": DistrictInfo(
        name="Nowshera", name_ur="نوشہرہ",
        province="KPK",
        avg_elevation_m=285,
        terrain_type="Plains", terrain_type_ur="میدانی",
        vulnerability_score=0.92,
        population_thousands=1600,
        lat=34.01, lon=71.97,
        rivers=["Kabul River", "Swat River"],
        flood_history_events=19,
        casualties_2022=47, displaced_2022=120,
        ndma_risk_zone="A",
    ),
    "charsadda": DistrictInfo(
        name="Charsadda", name_ur="چارسدہ",
        province="KPK",
        avg_elevation_m=276,
        terrain_type="Plains", terrain_type_ur="میدانی",
        vulnerability_score=0.88,
        population_thousands=1500,
        lat=34.15, lon=71.73,
        rivers=["Swat River", "Jindi River"],
        flood_history_events=17,
        casualties_2022=31, displaced_2022=95,
        ndma_risk_zone="A",
    ),
    "peshawar": DistrictInfo(
        name="Peshawar", name_ur="پشاور",
        province="KPK",
        avg_elevation_m=327,
        terrain_type="Urban Plains", terrain_type_ur="شہری میدانی",
        vulnerability_score=0.65,
        population_thousands=4300,
        lat=34.01, lon=71.57,
        rivers=["Kabul River", "Bara River"],
        flood_history_events=10,
        casualties_2022=12, displaced_2022=30,
        ndma_risk_zone="B",
    ),
    "mardan": DistrictInfo(
        name="Mardan", name_ur="مردان",
        province="KPK",
        avg_elevation_m=283,
        terrain_type="Semi-Plains", terrain_type_ur="نیم میدانی",
        vulnerability_score=0.72,
        population_thousands=2400,
        lat=34.20, lon=72.05,
        rivers=["Kalpani River"],
        flood_history_events=11,
        casualties_2022=18, displaced_2022=55,
        ndma_risk_zone="B",
    ),
    "dera ismail khan": DistrictInfo(
        name="Dera Ismail Khan", name_ur="ڈیرہ اسماعیل خان",
        province="KPK",
        avg_elevation_m=172,
        terrain_type="Plains", terrain_type_ur="میدانی",
        vulnerability_score=0.89,
        population_thousands=1800,
        lat=31.83, lon=70.90,
        rivers=["Indus River", "Gomal River"],
        flood_history_events=21,
        casualties_2022=58, displaced_2022=140,
        ndma_risk_zone="A",
    ),
    "dera ghazi khan": DistrictInfo(
        name="Dera Ghazi Khan", name_ur="ڈیرہ غازی خان",
        province="Punjab",
        avg_elevation_m=145,
        terrain_type="Plains", terrain_type_ur="میدانی",
        vulnerability_score=0.91,
        population_thousands=3200,
        lat=30.05, lon=70.63,
        rivers=["Indus River", "Chenab River"],
        flood_history_events=25,
        casualties_2022=112, displaced_2022=320,
        ndma_risk_zone="A",
    ),
    "rajanpur": DistrictInfo(
        name="Rajanpur", name_ur="راجن پور",
        province="Punjab",
        avg_elevation_m=132,
        terrain_type="Plains", terrain_type_ur="میدانی",
        vulnerability_score=0.93,
        population_thousands=2200,
        lat=29.10, lon=70.33,
        rivers=["Indus River"],
        flood_history_events=28,
        casualties_2022=87, displaced_2022=280,
        ndma_risk_zone="A",
    ),
    "muzaffargarh": DistrictInfo(
        name="Muzaffargarh", name_ur="مظفرگڑھ",
        province="Punjab",
        avg_elevation_m=128,
        terrain_type="Plains", terrain_type_ur="میدانی",
        vulnerability_score=0.90,
        population_thousands=4200,
        lat=30.07, lon=71.19,
        rivers=["Chenab River", "Indus River"],
        flood_history_events=23,
        casualties_2022=74, displaced_2022=250,
        ndma_risk_zone="A",
    ),
    "jacobabad": DistrictInfo(
        name="Jacobabad", name_ur="جیکب آباد",
        province="Sindh",
        avg_elevation_m=55,
        terrain_type="Low Plains", terrain_type_ur="نچلے میدانی",
        vulnerability_score=0.95,
        population_thousands=1200,
        lat=28.28, lon=68.43,
        rivers=["Indus River"],
        flood_history_events=30,
        casualties_2022=145, displaced_2022=380,
        ndma_risk_zone="A",
    ),
    "larkana": DistrictInfo(
        name="Larkana", name_ur="لاڑکانہ",
        province="Sindh",
        avg_elevation_m=48,
        terrain_type="Low Plains", terrain_type_ur="نچلے میدانی",
        vulnerability_score=0.87,
        population_thousands=2000,
        lat=27.55, lon=68.22,
        rivers=["Indus River"],
        flood_history_events=18,
        casualties_2022=63, displaced_2022=195,
        ndma_risk_zone="A",
    ),
    "sukkur": DistrictInfo(
        name="Sukkur", name_ur="سکھر",
        province="Sindh",
        avg_elevation_m=66,
        terrain_type="Plains", terrain_type_ur="میدانی",
        vulnerability_score=0.82,
        population_thousands=1600,
        lat=27.70, lon=68.86,
        rivers=["Indus River"],
        flood_history_events=16,
        casualties_2022=44, displaced_2022=120,
        ndma_risk_zone="A",
    ),
    "abbottabad": DistrictInfo(
        name="Abbottabad", name_ur="ایبٹ آباد",
        province="KPK",
        avg_elevation_m=1260,
        terrain_type="Hilly", terrain_type_ur="پہاڑی",
        vulnerability_score=0.55,
        population_thousands=1300,
        lat=34.15, lon=73.22,
        rivers=["Dor River"],
        flood_history_events=8,
        casualties_2022=9, displaced_2022=18,
        ndma_risk_zone="B",
    ),
    "mansehra": DistrictInfo(
        name="Mansehra", name_ur="مانسہرہ",
        province="KPK",
        avg_elevation_m=1070,
        terrain_type="Hilly", terrain_type_ur="پہاڑی",
        vulnerability_score=0.68,
        population_thousands=1500,
        lat=34.33, lon=73.20,
        rivers=["Kunhar River", "Siran River"],
        flood_history_events=13,
        casualties_2022=22, displaced_2022=60,
        ndma_risk_zone="B",
    ),

    # Punjab Province - Major Cities and Districts
    "lahore": DistrictInfo(
        name="Lahore", name_ur="لاہور",
        province="Punjab",
        avg_elevation_m=217,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.72,
        population_thousands=11000,
        lat=31.55, lon=74.34,
        rivers=["Ravi River"],
        flood_history_events=8,
        casualties_2022=15, displaced_2022=120,
        ndma_risk_zone="B",
    ),
    "karachi": DistrictInfo(
        name="Karachi", name_ur="کراچی",
        province="Sindh",
        avg_elevation_m=8,
        terrain_type="Coastal", terrain_type_ur="ساحلی",
        vulnerability_score=0.85,
        population_thousands=16000,
        lat=24.86, lon=67.01,
        rivers=["Malir River", "Lyari River"],
        flood_history_events=12,
        casualties_2022=45, displaced_2022=200,
        ndma_risk_zone="A",
    ),
    "islamabad": DistrictInfo(
        name="Islamabad", name_ur="اسلام آباد",
        province="Punjab",
        avg_elevation_m=540,
        terrain_type="Hilly", terrain_type_ur="پہاڑی",
        vulnerability_score=0.45,
        population_thousands=1100,
        lat=33.68, lon=73.05,
        rivers=["Soan River", "Kunhar River"],
        flood_history_events=5,
        casualties_2022=2, displaced_2022=8,
        ndma_risk_zone="C",
    ),
    "rawalpindi": DistrictInfo(
        name="Rawalpindi", name_ur="راولپنڈی",
        province="Punjab",
        avg_elevation_m=508,
        terrain_type="Hilly", terrain_type_ur="پہاڑی",
        vulnerability_score=0.65,
        population_thousands=5400,
        lat=33.60, lon=73.07,
        rivers=["Soan River", "Lai Nullah"],
        flood_history_events=9,
        casualties_2022=8, displaced_2022=35,
        ndma_risk_zone="B",
    ),
    "faisalabad": DistrictInfo(
        name="Faisalabad", name_ur="فیصل آباد",
        province="Punjab",
        avg_elevation_m=184,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.58,
        population_thousands=3800,
        lat=31.42, lon=73.08,
        rivers=["Chenab River"],
        flood_history_events=7,
        casualties_2022=12, displaced_2022=45,
        ndma_risk_zone="B",
    ),
    "multan": DistrictInfo(
        name="Multan", name_ur="ملتان",
        province="Punjab",
        avg_elevation_m=122,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.75,
        population_thousands=1900,
        lat=30.20, lon=71.47,
        rivers=["Chenab River", "Sutlej River"],
        flood_history_events=11,
        casualties_2022=18, displaced_2022=85,
        ndma_risk_zone="A",
    ),
    "gujranwala": DistrictInfo(
        name="Gujranwala", name_ur="گوجرانوالہ",
        province="Punjab",
        avg_elevation_m=230,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.62,
        population_thousands=5000,
        lat=32.16, lon=74.19,
        rivers=["Chenab River"],
        flood_history_events=6,
        casualties_2022=9, displaced_2022=28,
        ndma_risk_zone="B",
    ),
    "sialkot": DistrictInfo(
        name="Sialkot", name_ur="سیالکوٹ",
        province="Punjab",
        avg_elevation_m=256,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.55,
        population_thousands=2400,
        lat=32.50, lon=74.54,
        rivers=["Chenab River"],
        flood_history_events=4,
        casualties_2022=5, displaced_2022=15,
        ndma_risk_zone="C",
    ),

    # Sindh Province - Major Districts
    "hyderabad": DistrictInfo(
        name="Hyderabad", name_ur="حیدرآباد",
        province="Sindh",
        avg_elevation_m=13,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.82,
        population_thousands=2200,
        lat=25.37, lon=68.37,
        rivers=["Indus River"],
        flood_history_events=15,
        casualties_2022=32, displaced_2022=150,
        ndma_risk_zone="A",
    ),
    "sindh": DistrictInfo(
        name="Sindh Rural", name_ur="سندھ دیہی",
        province="Sindh",
        avg_elevation_m=15,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.88,
        population_thousands=800,
        lat=26.30, lon=68.40,
        rivers=["Indus River"],
        flood_history_events=18,
        casualties_2022=55, displaced_2022=280,
        ndma_risk_zone="A",
    ),

    # Balochistan Province - Major Districts
    "quetta": DistrictInfo(
        name="Quetta", name_ur="کوئٹہ",
        province="Balochistan",
        avg_elevation_m=1680,
        terrain_type="Mountain", terrain_type_ur="پہاڑی",
        vulnerability_score=0.52,
        population_thousands=1000,
        lat=30.18, lon=67.00,
        rivers=["Urak River"],
        flood_history_events=6,
        casualties_2022=8, displaced_2022=25,
        ndma_risk_zone="B",
    ),
    "gwadar": DistrictInfo(
        name="Gwadar", name_ur="گوادر",
        province="Balochistan",
        avg_elevation_m=5,
        terrain_type="Coastal", terrain_type_ur="ساحلی",
        vulnerability_score=0.78,
        population_thousands=90,
        lat=25.13, lon=62.33,
        rivers=["Dasht River"],
        flood_history_events=3,
        casualties_2022=2, displaced_2022=5,
        ndma_risk_zone="B",
    ),

    # Azad Kashmir - Major Districts
    "muzaffarabad": DistrictInfo(
        name="Muzaffarabad", name_ur="مظفرآباد",
        province="Azad Kashmir",
        avg_elevation_m=737,
        terrain_type="Mountain", terrain_type_ur="پہاڑی",
        vulnerability_score=0.75,
        population_thousands=725,
        lat=34.37, lon=73.47,
        rivers=["Jhelum River", "Neelum River"],
        flood_history_events=12,
        casualties_2022=28, displaced_2022=95,
        ndma_risk_zone="A",
    ),

    # Gilgit-Baltistan - Major Districts
    "gilgit": DistrictInfo(
        name="Gilgit", name_ur="گلگت",
        province="Gilgit-Baltistan",
        avg_elevation_m=1500,
        terrain_type="Mountain", terrain_type_ur="پہاڑی",
        vulnerability_score=0.65,
        population_thousands=216,
        lat=35.92, lon=74.31,
        rivers=["Gilgit River", "Hunza River"],
        flood_history_events=8,
        casualties_2022=12, displaced_2022=40,
        ndma_risk_zone="B",
    ),

    # Additional KPK Districts
    "kohat": DistrictInfo(
        name="Kohat", name_ur="کوہاٹ",
        province="KPK",
        avg_elevation_m=489,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.70,
        population_thousands=993,
        lat=33.58, lon=71.45,
        rivers=["Kohat Toi"],
        flood_history_events=9,
        casualties_2022=14, displaced_2022=35,
        ndma_risk_zone="B",
    ),
    "haripur": DistrictInfo(
        name="Haripur", name_ur="ہری پور",
        province="KPK",
        avg_elevation_m=610,
        terrain_type="Hilly", terrain_type_ur="پہاڑی",
        vulnerability_score=0.55,
        population_thousands=1003,
        lat=33.99, lon=72.93,
        rivers=["Dora River"],
        flood_history_events=6,
        casualties_2022=7, displaced_2022=20,
        ndma_risk_zone="C",
    ),

    # Additional Punjab Districts
    "sahiwal": DistrictInfo(
        name="Sahiwal", name_ur="ساہیوال",
        province="Punjab",
        avg_elevation_m=152,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.68,
        population_thousands=2472,
        lat=30.67, lon=73.11,
        rivers=["Sutlej River"],
        flood_history_events=8,
        casualties_2022=11, displaced_2022=42,
        ndma_risk_zone="B",
    ),
    # Additional Punjab Districts
    "sahiwal": DistrictInfo(
        name="Sahiwal", name_ur="ساہیوال",
        province="Punjab",
        avg_elevation_m=152,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.68,
        population_thousands=2472,
        lat=30.67, lon=73.11,
        rivers=["Sutlej River"],
        flood_history_events=8,
        casualties_2022=11, displaced_2022=42,
        ndma_risk_zone="B",
    ),
    "bahawalpur": DistrictInfo(
        name="Bahawalpur", name_ur="بہاولپور",
        province="Punjab",
        avg_elevation_m=118,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.73,
        population_thousands=3661,
        lat=29.40, lon=71.68,
        rivers=["Sutlej River"],
        flood_history_events=10,
        casualties_2022=16, displaced_2022=75,
        ndma_risk_zone="A",
    ),

    # Additional Sindh Districts
    "thatta": DistrictInfo(
        name="Thatta", name_ur="ٹھٹہ",
        province="Sindh",
        avg_elevation_m=8,
        terrain_type="Coastal", terrain_type_ur="ساحلی",
        vulnerability_score=0.85,
        population_thousands=979,
        lat=24.75, lon=67.92,
        rivers=["Indus River"],
        flood_history_events=12,
        casualties_2022=8, displaced_2022=35,
        ndma_risk_zone="A",
    ),
    "mirpurkhas": DistrictInfo(
        name="Mirpurkhas", name_ur="میرپور خاص",
        province="Sindh",
        avg_elevation_m=14,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.78,
        population_thousands=1504,
        lat=25.53, lon=69.01,
        rivers=["Indus River"],
        flood_history_events=9,
        casualties_2022=14, displaced_2022=65,
        ndma_risk_zone="A",
    ),
    "badin": DistrictInfo(
        name="Badin", name_ur="بدین",
        province="Sindh",
        avg_elevation_m=10,
        terrain_type="Coastal", terrain_type_ur="ساحلی",
        vulnerability_score=0.88,
        population_thousands=1801,
        lat=24.66, lon=68.84,
        rivers=["Indus River"],
        flood_history_events=15,
        casualties_2022=22, displaced_2022=95,
        ndma_risk_zone="A",
    ),
    "shikarpur": DistrictInfo(
        name="Shikarpur", name_ur="شیکارپور",
        province="Sindh",
        avg_elevation_m=12,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.82,
        population_thousands=1234,
        lat=27.96, lon=68.64,
        rivers=["Indus River"],
        flood_history_events=11,
        casualties_2022=18, displaced_2022=78,
        ndma_risk_zone="A",
    ),
    "ghotki": DistrictInfo(
        name="Ghotki", name_ur="گھوٹکی",
        province="Sindh",
        avg_elevation_m=11,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.79,
        population_thousands=1648,
        lat=28.00, lon=69.32,
        rivers=["Indus River"],
        flood_history_events=10,
        casualties_2022=15, displaced_2022=62,
        ndma_risk_zone="A",
    ),

    # Additional KPK Districts
    "bannu": DistrictInfo(
        name="Bannu", name_ur="بنوں",
        province="KPK",
        avg_elevation_m=332,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.65,
        population_thousands=1182,
        lat=32.99, lon=70.60,
        rivers=["Kurram River"],
        flood_history_events=7,
        casualties_2022=9, displaced_2022=28,
        ndma_risk_zone="B",
    ),

    # Additional Balochistan Districts
    "khuzdar": DistrictInfo(
        name="Khuzdar", name_ur="خضدار",
        province="Balochistan",
        avg_elevation_m=1234,
        terrain_type="Mountain", terrain_type_ur="پہاڑی",
        vulnerability_score=0.58,
        population_thousands=833,
        lat=27.80, lon=66.61,
        rivers=["Kech River"],
        flood_history_events=4,
        casualties_2022=3, displaced_2022=12,
        ndma_risk_zone="B",
    ),
    "sibi": DistrictInfo(
        name="Sibi", name_ur="سبی",
        province="Balochistan",
        avg_elevation_m=135,
        terrain_type="Desert", terrain_type_ur="صحرا",
        vulnerability_score=0.62,
        population_thousands=1035,
        lat=29.55, lon=67.88,
        rivers=["Nari River"],
        flood_history_events=5,
        casualties_2022=4, displaced_2022=18,
        ndma_risk_zone="B",
    ),
    "turbat": DistrictInfo(
        name="Turbat", name_ur="تربت",
        province="Balochistan",
        avg_elevation_m=6,
        terrain_type="Coastal", terrain_type_ur="ساحلی",
        vulnerability_score=0.71,
        population_thousands=213,
        lat=26.00, lon=63.05,
        rivers=["Dasht River"],
        flood_history_events=3,
        casualties_2022=1, displaced_2022=4,
        ndma_risk_zone="C",
    ),
    "loralai": DistrictInfo(
        name="Loralai", name_ur="لورالائی",
        province="Balochistan",
        avg_elevation_m=1415,
        terrain_type="Mountain", terrain_type_ur="پہاڑی",
        vulnerability_score=0.55,
        population_thousands=397,
        lat=30.37, lon=68.60,
        rivers=["Zhob River"],
        flood_history_events=3,
        casualties_2022=2, displaced_2022=8,
        ndma_risk_zone="C",
    ),
    "zhob": DistrictInfo(
        name="Zhob", name_ur="ژوب",
        province="Balochistan",
        avg_elevation_m=1442,
        terrain_type="Mountain", terrain_type_ur="پہاڑی",
        vulnerability_score=0.53,
        population_thousands=310,
        lat=31.34, lon=69.45,
        rivers=["Zhob River"],
        flood_history_events=2,
        casualties_2022=1, displaced_2022=5,
        ndma_risk_zone="C",
    ),
    "dera bugti": DistrictInfo(
        name="Dera Bugti", name_ur="ڈیرہ بگٹی",
        province="Balochistan",
        avg_elevation_m=161,
        terrain_type="Desert", terrain_type_ur="صحرا",
        vulnerability_score=0.59,
        population_thousands=313,
        lat=29.03, lon=69.15,
        rivers=["Bugti River"],
        flood_history_events=2,
        casualties_2022=1, displaced_2022=6,
        ndma_risk_zone="C",
    ),

    # Additional Punjab Districts
    "sheikhupura": DistrictInfo(
        name="Sheikhupura", name_ur="شیخوپورہ",
        province="Punjab",
        avg_elevation_m=207,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.64,
        population_thousands=3464,
        lat=31.71, lon=73.99,
        rivers=["Ravi River"],
        flood_history_events=6,
        casualties_2022=8, displaced_2022=32,
        ndma_risk_zone="B",
    ),
    "sargodha": DistrictInfo(
        name="Sargodha", name_ur="سرگودھا",
        province="Punjab",
        avg_elevation_m=191,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.61,
        population_thousands=3964,
        lat=32.08, lon=72.67,
        rivers=["Chenab River"],
        flood_history_events=7,
        casualties_2022=10, displaced_2022=38,
        ndma_risk_zone="B",
    ),
    "rahim yar khan": DistrictInfo(
        name="Rahim Yar Khan", name_ur="رحیم یار خان",
        province="Punjab",
        avg_elevation_m=88,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.76,
        population_thousands=4814,
        lat=28.42, lon=70.30,
        rivers=["Indus River", "Sutlej River"],
        flood_history_events=12,
        casualties_2022=19, displaced_2022=88,
        ndma_risk_zone="A",
    ),
    "kasur": DistrictInfo(
        name="Kasur", name_ur="قصور",
        province="Punjab",
        avg_elevation_m=194,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.67,
        population_thousands=3455,
        lat=31.12, lon=74.45,
        rivers=["Sutlej River"],
        flood_history_events=8,
        casualties_2022=12, displaced_2022=45,
        ndma_risk_zone="B",
    ),
    "okara": DistrictInfo(
        name="Okara", name_ur="اوکاڑہ",
        province="Punjab",
        avg_elevation_m=155,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.69,
        population_thousands=3042,
        lat=30.81, lon=73.45,
        rivers=["Ravi River"],
        flood_history_events=9,
        casualties_2022=14, displaced_2022=52,
        ndma_risk_zone="B",
    ),
    "jhelum": DistrictInfo(
        name="Jhelum", name_ur="جہلم",
        province="Punjab",
        avg_elevation_m=233,
        terrain_type="Plain", terrain_type_ur="میدان",
        vulnerability_score=0.63,
        population_thousands=1227,
        lat=32.94, lon=73.73,
        rivers=["Jhelum River"],
        flood_history_events=6,
        casualties_2022=7, displaced_2022=25,
        ndma_risk_zone="B",
    ),
}


def get_district(name: str) -> DistrictInfo | None:
    return DISTRICTS.get(name.strip().lower())


def get_all_districts() -> list[dict]:
    result = []
    for key, d in DISTRICTS.items():
        result.append({
            "id": key,
            "name": d.name,
            "name_ur": d.name_ur,
            "province": d.province,
            "avg_elevation_m": d.avg_elevation_m,
            "terrain_type": d.terrain_type,
            "terrain_type_ur": d.terrain_type_ur,
            "vulnerability_score": d.vulnerability_score,
            "population_thousands": d.population_thousands,
            "lat": d.lat,
            "lon": d.lon,
            "rivers": d.rivers,
            "flood_history_events": d.flood_history_events,
            "casualties_2022": d.casualties_2022,
            "displaced_2022": d.displaced_2022,
            "ndma_risk_zone": d.ndma_risk_zone,
        })
    return sorted(result, key=lambda x: x["vulnerability_score"], reverse=True)


def get_elevation_lookup() -> dict[str, float]:
    return {k: v.avg_elevation_m for k, v in DISTRICTS.items()}